#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication -s cold    decomposePar -region cold
#runApplication -s hot decomposePar -region hot

foamJob -parallel -screen chtMultiRegionFoam

runApplication -s cold    reconstructPar -latestTime -region cold
runApplication -s hot reconstructPar -latestTime -region hot
